---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - external-dns-charts.yaml
  - gissilabs-charts.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - k8s-gateway-charts.yaml
  - kubereboot-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - stakater-charts.yaml
