---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mosquitto-tls
spec:
  dnsNames:
    - "mosquitto.${SECRET_DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: "mosquitto-tls"
