---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mosquitto-tls
spec:
  secretName: mosquitto-tls
  dnsNames:
    - mosquitto.home.${SECRET_DOMAIN}
  issuerRef:
    name: letsencrypt-production
    kind: Issuer
    group: cert-manager.io
