---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  interval: 1h
  install:
    timeout: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/mosquitto/values.yaml

    # Backup
    podAnnotations:
      # backup.velero.io/backup-volumes: data
      configmap.reloader.stakater.com/reload: &config "mosquitto"
      secret.reloader.stakater.com/reload: &secrettls "mosquitto-tls"

    image:
      repository: eclipse-mosquitto
      tag: 2.0.15
    env:
      TZ: "${TIMEZONE}"

    # nodeSelector:
    #   role: iot-controller
    # tolerations:
    #   - key: "dedicated"
    #     operator: "Equal"
    #     value: "iot"
    #     effect: "NoSchedule"

    # TODO(fernandopn): Find a better solution
    # Internal DNS server
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - 10.0.6.211

    # Persistence
    # Storage
    persistence:
      configinc:
        enabled: true
        type: emptyDir
      config-import:
        enabled: true
        mountPath: /config
        type: custom
        volumeSpec:
          configMap:
            name: *config
      config-tls:
        enabled: true
        mountPath: /config-tls
        type: custom
        volumeSpec:
          secret:
            secretName: *secrettls
      data:
        enabled: true
        existingClaim: mosquitto

    initContainers:
      copy-config:
        image: busybox
        command: ['sh', '-c', 'cp /config/* /config-tls/* /mosquitto/configinc/']
        volumeMounts:
          - name: config-import
            mountPath: /config
          - name: config-tls
            mountPath: /config-tls
          - name: configinc
            mountPath: /mosquitto/configinc

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.0.6.227
        annotations:
          coredns.io/hostname: "mosquitto.${SECRET_DOMAIN}"
        ports:
          mqtttls:
            enabled: true
            port: 8883
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mosquitto-tls
  namespace: iot
spec:
  dnsNames:
    - "mosquitto.${SECRET_DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: *secrettls
