---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 10.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    # Backup
    podAnnotations:
      backup.velero.io/backup-volumes: data

    podLabels:
      app: node-red

    image:
      repository: nodered/node-red
      tag: 3.0.2
    env:
      TZ: "${SECRET_TIMEZONE}"

    # TODO(fernandopn): Find a better solution
    # Internal DNS server
    dnsPolicy: "ClusterFirstWithHostNet"
    # dnsConfig:
    #   nameservers:
    #     - 10.0.6.211

    # Pod
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "1"

    persistence:
      data:
        enabled: true
        existingClaim: node-red

    initContainers:
      update-config-ownership:
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
          - name: data
            mountPath: /data
        securityContext:
          runAsUser: 0
      update-config-permission:
        image: busybox
        command: ["sh", "-c", "chmod -R 770 /data"]
        volumeMounts:
          - name: data
            mountPath: /data
        securityContext:
          runAsUser: 0

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          coredns.io/hostname: &host "node-red.home.${SECRET_DOMAIN}"
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: node-red-tls
