---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 14m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: ingress-nginx
      namespace: networking

  values:
    image:
      repository: esphome/esphome
      tag: 2024.3.1

    podAnnotations:
      # secret.reloader.stakater.com/reload: esphome-config-deploykey
      # k8s.v1.cni.cncf.io/networks: macvlan-static-iot-esphome
      backup.velero.io/backup-volumes: config

    service:
      main:
        ports:
          http:
            port: 6052

    env:
      TZ: "${TIMEZONE}"
      ESPHOME_DASHBOARD_USE_PING: true

    # Pod
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"

    # Persistence
    persistence:
      config:
        enabled: true
        existingClaim: esphome

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          coredns.io/hostname: &host "esphome.home.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "chip"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
        hosts:
          - host: *host
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: esphome-tls

    addons:
      codeserver:
        enabled: true
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        volumeMounts:
          - name: config
            mountPath: /config
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            coredns.io/hostname: &host-vscode "esphome-vscode.home.${SECRET_DOMAIN}"
            hajimari.io/enable: "true"
            hajimari.io/icon: "code-greater-than"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          hosts:
            - host: *host-vscode
              paths:
                - path: /
          tls:
            - hosts:
                - *host-vscode
              secretName: esphome-vscode-tls
