# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rlUj9fAoZEZF5DR9NlaSyMA=,iv:6DaQqjx1nivI25pik0QFcwUEKJBWe4g1/aM2lARyFqs=,tag:xB4U0SCh/oKCh06XYgHGkg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:RJrp5XkADSsemSTZgkpUZOFuiJ9mZB2JC/l+zWStXSrN7i7Nyw==,iv:MYh7v1B8J0D4B+PqfVUot5R7NTp4QXmF2vtnfDCQl+4=,tag:9UhTuGnZZDjSA1cJv3ODMw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:jy90JU+aJAwusXTWtXmRHA==,iv:Di1LgFKE59X17LuogB+0wisdyAS/XQT0DRwrHdy9HgU=,tag:9wrwcw9ASp3Zezv0KrY40Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wxwc3qnqwcjhkxdkqh0junrysxp6y52uax2nnhtqmy8wg38uhfhqu60x3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNGswZk1Xb1U5aGNDMU1x
            U2NROE1XTVFQMnVTZHJWQ1NTOXo2YjR3VXpvClE1NHpBbW1RNDhFaTJLbDYwUzFU
            Z2h0c2c1OVFVeUl6b2tKNkhWbEVUNzQKLS0tIEJEbGo1VnRCNUUrYkZGLzcydUZo
            YUEveEIxYithYkNvWnlCWUl2SldGaDAKSVCrHppCCZ0ZG56+qp7Z2kD60U0TiElv
            HdO/np4XYW3H8n6fCD6xJEG67MxR+Y5iLMxYPqM8fLw9mk0Af1Ns6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-13T19:48:03Z"
    mac: ENC[AES256_GCM,data:PKNyaQsFTv2QP0Xj734DX110UJDm9udhUVCIIeS0ibduBu9QkltbE6kiSiFp3hVAYKnvUzyyKm9hEtG/z/KXW+VDCTlLzzqWzEgAk+ZmRIatfCRz5QvYa5Fjy5PHD19OikMXbEqbWyKTUAWXeoW+g507Ve/n/shCjKtmDaOoMUs=,iv:P9vKVqkJPW49f4wWjy6+WZTYCpLZ0dgUdaqr99JlOsg=,tag:tAiIDvlMXPM8niJNfVhwYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
