---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: mosquitto
      namespace: home-automation
    - name: ingress-nginx
      namespace: networking

  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.12.9

    # Backup
    podAnnotations:
      # secret.reloader.stakater.com/reload: home-assistant-secrets
      # k8s.v1.cni.cncf.io/networks: macvlan-static-iot-hass
      backup.velero.io/backup-volumes: config

    env:
      TZ: "${TIMEZONE}"

    # Pod
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 200m
        memory: 700Mi

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    # Persistence
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant

    # Homekit integration
    hostNetwork: true
    service:
      main:
        ports:
          http:
            port: 8123
      homekit:
        enabled: true
        type: "LoadBalancer"
        loadBalancerIP: 10.0.6.226
        ports:
          homekit:
            enabled: true
            port: 21065
            protocol: TCP

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          coredns.io/hostname: &host "home-assistant.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
        hosts:
          - host: *host
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: home-assistant-tls
