---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: daemonset
      strategy: RollingUpdate

    image:
      repository: docker.io/intel/intel-gpu-plugin
      tag: 0.26.0

    args:
      - -shared-dev-num
      - "2"

    # No need to deploy it on Arm machines.
    nodeSelector:
      kubernetes.io/arch: amd64

    service:
      main:
        enabled: false

    ingress:
      main:
        enabled: false

    persistence:
      devfs:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        hostPathType: Directory
        readOnly: true
      sysfs:
        enabled: true
        type: hostPath
        hostPath: /sys/class/drm
        hostPathType: Directory
        readOnly: true
      kubeletsockets:
        enabled: true
        type: hostPath
        hostPathType: Directory
        hostPath: /var/lib/kubelet/device-plugins

    # TODO(intel-gpu-plugin): Write probes to check for something to tell if it's working
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 30m
        memory: 64M
