---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudfare-tunnel
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  values:
    image:
      repository: cloudflare/cloudflared
      tag: 2024.4.1

    args:
      - --no-autoupdate
      - --hello-world

    service:
      main:
        enabled: false
