---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-exporter
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: speedtest-exporter
  endpoints:
    - interval: 10m
      port: http
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: speedtest-exporter
  labels:
    role: alert-rules
spec:
  groups:
    - name: speedtest
      rules:
        - alert: SpeedtestSlowInternetDownload
          annotations:
            message: Internet download speed is averaging {{ "{{ humanize $value }}" }} Mbps.
          expr: |
            avg_over_time(speedtest_download_bits_per_second{job=~".*{{ include "common.names.fullname" . }}.*"}[4h])
              < (800*1024*1024)
          for: 15m
          labels:
            severity: warning
        - alert: SpeedtestSlowInternetUpload
          annotations:
            message: Internet upload speed is averaging {{ "{{ humanize $value }}" }} Mbps.
          expr: |
            avg_over_time(speedtest_download_bits_per_second{job=~".*{{ include "common.names.fullname" . }}.*"}[4h])
              < (80*1024*1024)
          for: 15m
          labels:
            severity: warning
