---
kubernetes:
  children:
    master:
      hosts:
        thor:
          ansible_host: 10.0.6.252
    worker:
      # hosts:
      #   cactuar:
      #     ansible_host: 10.0.6.251
      #   hurricane:
      #     ansible_host: 10.0.6.249
