---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: velero-source
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/vmware-tanzu/helm-charts.git
  ref:
    # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts chart=velero
    tag: velero-5.1.0
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/charts/velero/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds-velero
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: velero-source
