# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:QakR8k2fkAAN9Kdmxq1OuQ8=,iv:wVCvVl/RQt0Y8u2Q5uNSc7s05A4ZL7P8+3Q6W7oBqV0=,tag:7cSnSn+AN+TD1xLmuQkBlA==,type:str]
    api-key: ENC[AES256_GCM,data:MinSLJ/wBgZLQnUuPiKkYO5NQpreJzBKVS1OrcpYDJkyU9tTJA==,iv:07i44uizCMw/Z6FJxOJDJXcYIeeeoyZ/loyZomLgm9U=,tag:Y+Q3SPZidE9ADc9bvopt9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wxwc3qnqwcjhkxdkqh0junrysxp6y52uax2nnhtqmy8wg38uhfhqu60x3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NDl2YlhnRTdKR2JOSXQ0
            eFVGU2RxVXVnVHovQkpPckJveTcvVEJ5LzJNCnUwMXlsYnBNRTl5MklHZ0JoSE95
            TGorZFVBTUdCc1Q1M1FqcGJnQkpzQm8KLS0tIHdJcUtkSUdQQlpyYVVTMlljbWFm
            MjA4TGFoQ2VxOURlMm8vK21VMzlvMEEKHa+t22RCzW5NcaVxg4QJ7T+rZKf1sHq0
            VDwXeKVsGQiqVWdNwKdzQ5wCGY3oC4HL1Af6ABd9wSly/kpqjqZoAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T20:05:07Z"
    mac: ENC[AES256_GCM,data:eDjgbFylC5EC9aoC4B5K5PIIRny30KwAEtO2twQruhpX+SD2jE/ifU/NasoUqyvvysTSxDgWAKh8UBsFzg0d2pDDiOJpAXAutpcTCSL2z0Imw/BkMd1Z1PLXGoZYMbe+Mka3xpaAWtDftbf3y+I6lSwvHJyooTack15rFw0i6kA=,iv:I3sRfkdADHMjylbXHbArJqrh+KZCV/DeHmY6Nndksxg=,tag:H/umBYkS3t5lbZ/lfdzDmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
