---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  releaseName: velero
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 6.6.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  interval: 1h
  # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
  values:
    image:
      repository: velero/velero
      tag: v1.14.0
    deployNodeAgent: true

    # This job upgrades the CRDs.
    installCRDs: false
    upgradeCRDs: false

    initContainers:
      - name: velero-plugin-for-gcp
        image: velero/velero-plugin-for-gcp:v1.9.1
        volumeMounts:
          - mountPath: /target
            name: plugins

    credentials:
      existingSecret: gcp-credentials

    schedules:
      mybackup:
        disabled: false
        schedule: "@every 24h"
        useOwnerReferencesInBackup: false
        template:
          includedResources: ["pods"]

    configuration:
      backupStorageLocation:
        - name: default
          bucket: ${SECRET_VELERO_BUCKET}
          prefix: cluster
          provider: gcp
      volumeSnapshotLocation:
        - name: default
          bucket: ${SECRET_VELERO_BUCKET}
          provider: gcp
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    resources:
      requests:
        memory: 128m
        cpu: 25m
      limits:
        memory: 1500Mi
    nodeAgent:
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
