# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ycBni5yegYknYUZWfS1lI1Q=,iv:35gH5D46cgBj6TvomGnaSxDjANCvJHcb54EezQKhV+0=,tag:Rw1OXcu+QSXhQY0ywL3FpA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:70juRKSJYuCwy8g=,iv:PPuIbxdxHe7lccb9HP3zarcJGTUMKbsopTK/gDus970=,tag:Z1qKqZP51cFf6nV3TPTyxg==,type:str]
    SECRET_STORAGE_ADDRESS: ENC[AES256_GCM,data:OaUvAaiGSaQjQg==,iv:/Rkg5KGGsMRisiNph6WG1UaGyC8GtU2Hnj641NWirYY=,tag:gQrqZRkddBS2LvjYtZwiXw==,type:str]
    SECRET_STORAGE_IQN: ENC[AES256_GCM,data:HIVwN5qZOr5EFB4TT1LkOqXcGVZRv8eB,iv:XonXmvS31eGzV8QUcHeQh7mtXR6ezQTMMjLyU2poOts=,tag:/7wj7RxTyZacn86EeHWHZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wxwc3qnqwcjhkxdkqh0junrysxp6y52uax2nnhtqmy8wg38uhfhqu60x3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZ2NCblZkYlE1djZRakMz
            U3FwVVJYOWpwUzdiVHp6ZmMzRGxFZUk0SkZvCmgzOVdnQnlPeFVqQVZyN1lRcUdP
            czBwTHlhZFF2R0xTN0lwRlBFaGZ2MkUKLS0tIEFoYVFvWjNSM2dacWFad1NVTVY0
            bEF1bHFkNGRXMEdRZ05VSThFbXBCdGcK7kHGQE8yYUSXnDafiqObREIFxGYLvg3I
            4xvX8RjJVojzadKjJf41W27JO+/WHjLNt8I/9u218A9E+3FloeFbbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T22:05:47Z"
    mac: ENC[AES256_GCM,data:mNHS3fdoaXujZrMIQMPrg0MTWcdT+lyyNHxMSiMVucWJa+dFpFsq0ykZuhSzrZhJyZh4YQdYDoInNp+LEE04AzQFWIJC9Q1TNzb8PWhF8T1wuO3zehc2VDCiHfalIbbCOuARclrPlqbdh1LQ7njzTDR9LZTWE5senBv+15WrnS4=,iv:xKWgLVuGudJMnmzEmv4Kc1OcD2g7lQuaknmRNmuG95k=,tag:hiIfCD4ShK7PORn93o/EQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
