---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/UTC
  METALLB_LB_RANGE: 10.0.6.210-10.0.6.230
  METALLB_K8S_GATEWAY_ADDR: 10.0.6.211
  METALLB_INGRESS_ADDR: 10.0.6.221
  METALLB_INGRESS_ADDR_LOCAL: 10.0.6.222
