---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: uptime-kuma
  endpoints:
    - interval: 15s
      port: http
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: uptime-kuma
  labels:
    role: alert-rules
spec:
  groups:
    - name: uptimeKuma
      rules:
        - alert: uptimeKumaDown
          annotations:
            message: Uptime Kuma noticed that {{ $labels.monitor_name }} is currently down.
          expr: |-
            monitor_status == 0
          for: 5m
          labels:
            severity: warning
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: bad-uplink
  labels:
    role: alert-rules
spec:
  groups:
    - name: uplink
      rules:
        - alert: badUplink
          annotations:
            message: The router uplink is not connected at 1G
          expr: |-
            unifipoller_device_wan_speed_bps != 1000000000
          for: 5m
          labels:
            severity: warning
