---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.21.2

    # Backup
    podAnnotations:
      # secret.reloader.stakater.com/reload: home-assistant-secrets
      # k8s.v1.cni.cncf.io/networks: macvlan-static-iot-hass
      backup.velero.io/backup-volumes: data

    env:
      TZ: "${TIMEZONE}"

    persistence:
      data:
        enabled: true
        existingClaim: uptime-kuma
        path: /app/data

    service:
      main:
        enabled: true
        ports:
          http:
            port: 3001

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          coredns.io/hostname: &host "uptime-kuma.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "alert-decagram"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: uptime-kuma-tls
