---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 3

  values:
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/plex/values.yaml
    image:
      repository: plexinc/pms-docker
      tag: 1.29.0.6244-819d3678c

    # Backup
    podAnnotations:
      backup.velero.io/backup-volumes: config

    podSecurityContext: # Plex container runAS plex:plex (1000:1000)
      # runAsUser: 1000
      # runAsGroup: 1000
      # fsGroup: 1000
      # fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44 # video
        - 100 # users

    initContainers:
      update-volume-permission:
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0

    # Pod
    resources:
      requests:
        # gpu.intel.com/i915: 1
        cpu: 1
        memory: 6Gi
      limits:
        # gpu.intel.com/i915: 1
        cpu: 4
        memory: 10Gi

    # Persistence
    persistence:
      # Make sure it has pid/gid 568
      # and it is pre-populated
      config:
        enabled: true
        existingClaim: plex
      movies:
        enabled: true
        existingClaim: movie
        mountPath: /movies
      tv:
        enabled: true
        existingClaim: tv
        mountPath: /tv
      transcode:
        enabled: true
        type: emptyDir

    # Network
    hostNetwork: true
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.6.228
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: plex
        port:
          port: 32400

    ingress:
      main:
        enabled: true
        annotations:
          coredns.io/hostname: &host "plex.home.${SECRET_DOMAIN}"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: plex-tls
