---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system

  values:
    # nodeSelector:
    #   role: iot-controller
    # tolerations:
    #   - key: "dedicated"
    #     operator: "Equal"
    #     value: "iot"
    #     effect: "NoSchedule"

    # Backup
    # podAnnotations:
    #   backup.velero.io/backup-volumes: data

    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.28.0

    # Pod
    securityContext:
      privileged: true
    podSecurityContext:
      supplementalGroups:
        - 20 # dialout
    strategy: # Need to turn down then turn up (depend on one usb device)
      type: Recreate
    env:
      TZ: "${SECRET_TIMEZONE}"

    # Pod
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "250m"

    # Persistence
    persistence:
      data:
        enabled: true
        existingClaim: zigbee2mqtt
      usb:
        enabled: true
        hostPath: /dev/ttyUSB0
        mountPath: /dev/ttyUSB0

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          coredns.io/hostname: &host "zigbee2mqtt.home.${SECRET_DOMAIN}"
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: zigbee2mqtt-tls

    addons:
      codeserver:
        enabled: true
        workingDir: "/data"
        args:
          - --user-data-dir
          - "/data/.vscode"
          - --auth
          - "none"
        volumeMounts:
          - name: data
            mountPath: /data
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            coredns.io/hostname: &host-vscode "zigbee2mqtt-vscode.home.${SECRET_DOMAIN}"
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          hosts:
            - host: *host-vscode
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host-vscode
              secretName: zigbee2mqtt-vscode-tls
