---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: home-assistant
      namespace: home-automation
    - name: ingress-nginx
      namespace: networking

  values:
    image:
      repository: nodered/node-red
      tag: 3.0.2

    # Backup
    podAnnotations:
      backup.velero.io/backup-volumes: data

    podLabels:
      app: node-red

    env:
      TZ: "${SECRET_TIMEZONE}"
      FLOWS: flows.json

    # Pod
    resources:
      requests:
        memory: "68Mi"
        cpu: "20m"
      limits:
        memory: "128Mi"
        cpu: "40m"

    persistence:
      data:
        enabled: true
        existingClaim: node-red

    initContainers:
      update-config-ownership:
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
          - name: data
            mountPath: /data
        securityContext:
          runAsUser: 0
      update-config-permission:
        image: busybox
        command: ["sh", "-c", "chmod -R 770 /data"]
        volumeMounts:
          - name: data
            mountPath: /data
        securityContext:
          runAsUser: 0

    service:
      main:
        ports:
          http:
            port: 1880

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          coredns.io/hostname: &host "node-red.home.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "transit-connection-variant"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: node-red-tls
