---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  values:
    image:
      repository: golift/unifi-poller
      tag: 2.1.3
    env:
      TZ: "${TIMEZONE}"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_URL: "${SECRET_UNIFI_URL}"
      UP_UNIFI_DEFAULT_USER: "${SECRET_UNIFI_DEFAULT_USER}"
      UP_UNIFI_DEFAULT_PASS: "${SECRET_UNIFI_DEFAULT_PASS}"
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: false
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
      UP_PROMETHEUS_NAMESPACE: "unifipoller"

    # Pod
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "1"

    service:
      main:
        enabled: true
        ports:
          metrics:
            port: 9130

    metrics:
      enabled: true
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
        enabled: true
        labels:
          release: kube-prometheus-stack

      prometheusRule:
        enabled: true
        labels:
          role: alert-rules
        rules:
          - alert: UnifiPollerAbsent
            annotations:
              description: Unifi Poller has disappeared from Prometheus service discovery.
              summary: Unifi Poller is down.
            expr: |
              absent(up{job=~".*{{ include "common.names.fullname" . }}.*"} == 1)
            for: 5m
            labels:
              severity: critical
