---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi-poller
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: golift/unifi-poller
      tag: 2.1.3
    env:
      TZ: "${TIMEZONE}"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_URL: "${SECRET_UNIFI_URL}"
      UP_UNIFI_DEFAULT_USER: "${SECRET_UNIFI_DEFAULT_USER}"
      UP_UNIFI_DEFAULT_PASS: "${SECRET_UNIFI_DEFAULT_PASS}"
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: false
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
      UP_PROMETHEUS_NAMESPACE: "unifipoller"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack
