---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: ${SECRET_STORAGE_ADDRESS}
    iqn: ${SECRET_STORAGE_IQN}:kube-prometheus
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthSession: true
    secretRef:
      name: storage-secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: ${SECRET_STORAGE_ADDRESS}
    iqn: ${SECRET_STORAGE_IQN}:kube-grafana
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthSession: true
    secretRef:
      name: storage-secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: ${SECRET_STORAGE_ADDRESS}
    iqn: ${SECRET_STORAGE_IQN}:kube-alertmanager
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthSession: true
    secretRef:
      name: storage-secret
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: grafana
