---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: v1.11.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: ingress-nginx
      namespace: networking

  values:
    # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
    installCRDs: false
    webhook:
      enabled: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only
    replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "9.9.9.9"
