---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: magrathea-tls
spec:
  dnsNames:
    - "magrathea.home.${SECRET_DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: "magrathea-tls"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unify-tls
spec:
  dnsNames:
    - "unify.home.${SECRET_DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: "unify-tls"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pikvm-tls
spec:
  dnsNames:
    - "pikvm.home.${SECRET_DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: "pikvm-tls"
