kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: not-important
spec:
  install:
    remediation:
      retries: 3
  values:
    # Auto media should only run on intel/amd
    nodeSelector:
      kubernetes.io/arch: amd64

    remediation:
      retries: 3
    # Pod
    strategy: # Need to turn down then turn up (depend on one persistent volume)
      type: Recreate
    env:
      TZ: "${SECRET_TIMEZONE}"

    # Persistence
    persistence:
      config:
        skipuninstall: true

    # Ingress
    ingress:
      main:
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
