apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: not-important
spec:
    values:
        addons:
            vpn:
                enabled: true
                type: openvpn
                openvpn:
                    auth: unsyombuoits;xJMO3DprvGjVdEqi%c8W&
                env:
                    ROUTE_1: 10.0.0.0/8
                configFile: |-
                    client
                    dev tun
                    proto udp
                    remote waw-023.vpn.privado.io 1194
                    resolv-retry infinite
                    nobind
                    persist-key
                    persist-tun
                    persist-remote-ip
                    verify-x509-name waw-023.vpn.privado.io name
                    auth-user-pass
                    #comp-lzo
                    verb 3
                    auth SHA256
                    cipher AES-256-CBC
                    tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA:TLS-DHE-DSS-WITH-AES-256-CBC-SHA:TLS-RSA-WITH-AES-256-CBC-SHA
                    <ca>
                    -----BEGIN CERTIFICATE-----
                    MIIFKDCCAxCgAwIBAgIJAMtrmqZxIV/OMA0GCSqGSIb3DQEBDQUAMBIxEDAOBgNV
                    BAMMB1ByaXZhZG8wHhcNMjAwMTA4MjEyODQ1WhcNMzUwMTA5MjEyODQ1WjASMRAw
                    DgYDVQQDDAdQcml2YWRvMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
                    xPwOgiwNJzZTnKIXwAB0TSu/Lu2qt2U2I8obtQjwhi/7OrfmbmYykSdro70al2XP
                    hnwAGGdCxW6LDnp0UN/IOhD11mgBPo14f5CLkBQjSJ6VN5miPbvK746LsNZl9H8r
                    QGvDuPo4CG9BfPZMiDRGlsMxij/jztzgT1gmuxQ7WHfFRcNzBas1dHa9hV/d3TU6
                    /t47x4SE/ljdcCtJiu7Zn6ODKQoys3mB7Luz2ngqUJWvkqsg+E4+3eJ0M8Hlbn5T
                    PaRJBID7DAdYo6Vs6xGCYr981ThFcmoIQ10js10yANrrfGAzd03b3TnLAgko0uQM
                    HjliMZL6L8sWOPHxyxJI0us88SFh4UgcFyRHKHPKux7w24SxAlZUYoUcTHp9VjG5
                    XvDKYxzgV2RdM4ulBGbQRQ3y3/CyddsyQYMvA55Ets0LfPaBvDIcct70iXijGsdv
                    lX1du3ArGpG7Vaje/RU4nbbGT6HYRdt5YyZfof288ukMOSj20nVcmS+c/4tqsxSe
                    rRb1aq5LOi1IemSkTMeC5gCbexk+L1vl7NT/58sxjGmu5bXwnvev/lIItfi2AlIT
                    rfUSEv19iDMKkeshwn/+sFJBMWYyluP+yJ56yR+MWoXvLlSWphLDTqq19yx3BZn0
                    P1tgbXoR0g8PTdJFcz8z3RIb7myVLYulV1oGG/3rka0CAwEAAaOBgDB+MB0GA1Ud
                    DgQWBBTFtJkZCVDuDAD6k5bJzefjJdO3DTBCBgNVHSMEOzA5gBTFtJkZCVDuDAD6
                    k5bJzefjJdO3DaEWpBQwEjEQMA4GA1UEAwwHUHJpdmFkb4IJAMtrmqZxIV/OMAwG
                    A1UdEwQFMAMBAf8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBDQUAA4ICAQB7MUSX
                    MeBb9wlSv4sUaT1JHEwE26nlBw+TKmezfuPU5pBlY0LYr6qQZY95DHqsRJ7ByUzG
                    UrGo17dNGXlcuNc6TAaQQEDRPo6y+LVh2TWMk15TUMI+MkqryJtCret7xGvDigKY
                    MJgBy58HN3RAVr1B7cL9youwzLgc2Y/NcFKvnQJKeiIYAJ7g0CcnJiQvgZTS7xdw
                    kEBXfsngmUCIG320DLPEL+Ze0HiUrxwWljMRya6i40AeH3Zu2i532xX1wV5+cjA4
                    RJWIKg6ri/Q54iFGtZrA9/nc6y9uoQHkmz8cGyVUmJxFzMrrIICVqUtVRxLhkTMe
                    4UzwRWTBeGgtW4tS0yq1QonAKfOyjgRw/CeY55D2UGvnAFZdTadtYXS4Alu2P9zd
                    woEk3fzHiVmDjqfJVr5wz9383aABUFrPI3nz6ed/Z6LZflKh1k+DUDEp8NxU4klU
                    ULWsSOKoa5zGX51G8cdHxwQLImXvtGuN5eSR8jCTgxFZhdps/xes4KkyfIz9FMYG
                    748M+uOTgKITf4zdJ9BAyiQaOufVQZ8WjhWzWk9YHec9VqPkzpWNGkVjiRI5ewuX
                    wZzZ164tMv2hikBXSuUCnFz37/ZNwGlDi0oBdDszCk2GxccdFHHaCSmpjU5MrdJ+
                    5IhtTKGeTx+US2hTIVHQFIO99DmacxSYvLNcSQ==
                    -----END CERTIFICATE-----
                    </ca>
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wxwc3qnqwcjhkxdkqh0junrysxp6y52uax2nnhtqmy8wg38uhfhqu60x3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUmpTK0RvT1AwaXkyM0hI
            YXpIWXhGYVR6RjBuWXl4cjd2ZFcwU2xPTzFvClFlMER2TFVydEVkeDlEMFY0b2Ew
            SjB2cS8wZXZZRU50VThHcXM4RVFDT3MKLS0tIEx3QXJrRXh6MWZUK0tMR1dVNEF1
            SDYzME5jWWNpNWpRZXFlZjJFL1kzR00KYkkwgs+LPHvYNuDW8NcZPwbxBb01f/+E
            YjEeGSy6qgUZjeG/iN7s0BT1ISZuf5+WRrd3ydrUAZ8LlBfuGOTK0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-11T19:29:16Z"
    mac: ENC[AES256_GCM,data:vVJHUAAsVGoD4haTtU788Va31E2Wapmi0Xbk5Xv1ASW9qB+33I+8FJ96MJq3K84xZcE3f84mwhID1/9ozwlBz3+CV8JBltHpLW7Ig39JkCj4Ta56cVi70Q7RMnP4AoS1sw4o8UHukzOPs0jAtmj3+3jq/0hPhBymknGHS8W/4AE=,iv:L4h4U5Wsm5Wq5ATeRi6EcZv6zljGDVMLrYaTuco0w2s=,tag:K1558eboPXQ0cHrESiWdMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
