---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: mosquitto
      namespace: home-automation
    - name: ingress-nginx
      namespace: networking

  values:
    image:
      repository: docker.io/koenkk/zigbee2mqtt
      tag: 1.28.0

    nodeSelector:
      kubernetes.io/hostname: cactuar

    # Backup
    podAnnotations:
      backup.velero.io/backup-volumes: data

    env:
      TZ: "${SECRET_TIMEZONE}"
      # ZIGBEE2MQTT_DATA: /data

    # Pod
    securityContext:
      privileged: true

    podSecurityContext:
      supplementalGroups:
        - 20 # dialout
    strategy: # Need to turn down then turn up (depend on one usb device)
      type: Recreate

    # Pod
    resources:
      requests:
        cpu: 15m
        memory: 192Mi
      limits:
        cpu: 30m
        memory: 256Mi

    # Persistence
    persistence:
      data:
        enabled: true
        mountPath: "/data"
        existingClaim: zigbee2mqtt
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
        mountPath: /dev/ttyUSB0

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          coredns.io/hostname: &host "zigbee2mqtt.home.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-automation"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
        hosts:
          - host: *host
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: zigbee2mqtt-tls

    addons:
      codeserver:
        enabled: true
        workingDir: "/data"
        args:
          - --user-data-dir
          - "/data/.vscode"
          - --auth
          - "none"
        volumeMounts:
          - name: data
            mountPath: /data
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            coredns.io/hostname: &host-vscode "zigbee2mqtt-vscode.home.${SECRET_DOMAIN}"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          hosts:
            - host: *host-vscode
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host-vscode
              secretName: zigbee2mqtt-vscode-tls
