---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/system-upgrade-controller?ref=v0.13.0
  - plans
images:
  - name: rancher/system-upgrade-controller
    newName: docker.io/rancher/system-upgrade-controller
    newTag: v0.11.0
commonLabels:
  app.kubernetes.io/name: system-upgrade-controller
  app.kubernetes.io/instance: system-upgrade-controller
patchesStrategicMerge:
  # Delete namespace resource
  - |
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: system-upgrade
