---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 15m
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    # https://github.com/toboshii/hajimari/blob/main/charts/hajimari/values.yaml
    hajimari:
      globalBookmarks:
        - group: Control
          bookmarks:
            - name: Github Repo
              url: "https://github.com/fernandopn/swarm-mind"
        - group: Media
          bookmarks:
            - name: Plex
              url: "https://plex.tv"
      namespaceSelector:
        matchNames:
          - default
          - networking
          - media
          - home-automation
          - storage
      name: "Keeper"
      lightTheme: "gazette"
      darkTheme: "blackboard"

    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          coredns.io/hostname: &host "${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "hajimari-tls"
